language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export DJANGO_SETTINGS_MODULE=exposure.settings
install:
  - pip install -r requirements.txt
before_script:
  - flake8 exposure --exclude=migrations
script:
  - python manage.py test